/*
 * HEATING_ELEMENT_LED.c
 *
 *  Author: toby
 */ 

#include "HEATING_ELEMENT_LED.h"
#include "main.h"
void HEATING_ELEMENT_LED_INIT(void){
	DIO_Direction(DIO_PORTC,HEATING_ELEMENT_LED_PIN,DIO_OUTPUT);
}
void HEATING_ELEMENT_LED_ON(void)
{
	DIO_value(DIO_PORTC,HEATING_ELEMENT_LED_PIN,DIO_HIGH);
}
void HEATING_ELEMENT_LED_OFF(void){
	DIO_value(DIO_PORTC,HEATING_ELEMENT_LED_PIN,DIO_LOW);
}
void HEATING_ELEMENT_LED_TOGGLE(void)
{
	DIO_TGL(DIO_PORTC,HEATING_ELEMENT_LED_PIN);
}